DRAFT: Re-align queries with Drupal implementation
instituteforgov/ifg-ministers-database-public pull request #5
Opened 2024-06-04 07:07 UTC by graham73may

2024-06-13 17:24 UTC, philipnye requested changes
I've flagged with comments a few points that don't look right to me.

Could we also change dashes to underscores in the eight `...merged-result-count.sql` script names?

Thanks!

2024-06-13 17:24 UTC, philipnye commented on sql/4_appointments_exits_between_dates/4_table_data_merged-result-count.sql
While on the inputs I've tested this is giving the correct count, I think it might be safer to use the same approach as I've added in the comment on `1_appointments_held_by_person/1_table_data_merged-result-count.sql` - i.e. doing the `SELECT..COUNT` as an extra outer layer

2024-06-13 17:24 UTC, philipnye commented on sql/3_appointments_at_date/3_table_data_merged-result-count.sql
As with `1_appointments_held_by_person/1_table_data_merged-result-count.sql`, this isn't giving me the right count on the inputs I've tested it with (146 vs 141): 'date': '2021-09-30'.

As with the other `...merged-result-count.sql` scripts, I think extracting the `SELECT..COUNT` to an encompassing query would resolve this.

2024-06-14 07:22 UTC, graham73may commented on sql/1_appointments_held_by_person/1_related_content.sql
The value we have available to work with from the frontend is the minister's name: 

![image](https://github.com/instituteforgov/ifg-ministers-database-public/assets/6642498/ab2e48b1-efdb-4685-98a7-c9cb086a2178)

For reference, the autocomplete itself is populated by:

```php
    $sql[] = 'SELECT p.id, p.display_name, LOWER(p.display_name) AS "lowercase_name"';
    $sql[] = 'FROM person p';

    if (!empty($input)) {
      $sql[] = 'WHERE ';

      // Ignore the order the words are inputted in. Eg, 'camer david'
      // should pull up 'David Cameron'.
      $words = explode(' ', $input);
      $display_name_conditions = [];

      foreach ($words as $index => $word) {
        $word = trim($word);

        if (!empty($word)) {
          $display_name_conditions[] = 'p.display_name LIKE :name' . $index;
          $arguments[':name' . $index] = '%' . strtolower($word) . '%';
        }
      }

      if ($display_name_conditions) {
        $sql[] = '(' . implode(' AND ', $display_name_conditions) . ')';
      }
    }

    $sql[] = 'ORDER BY p.display_name ASC';

```

2024-06-14 07:31 UTC, graham73may commented
> I've flagged with comments a few points that don't look right to me.
> 
> Could we also change dashes to underscores in the eight `...merged-result-count.sql` script names?
> 
> Thanks!

Hi @philipnye 

Comments look good I've pushed the file name change already to get that out of the way. 

I'll need to look into the count() stuff, your suggestion make sense, I just need to work out how to implement it into what we've got in PHP.

I'll need to dig a bit deeper into exactly why some things are names vs ids, but from memory it's because of the multiple results for the autocomplete if they're not grouped/distinct. 

e.g. the autocomplete field is showing

- Bob
- John
- Steve

But without the grouping or distinct (can't remember which) the autocomplete would show as 

- Bob
- Bob
- Bob
- John
- Steve
- Steve

When you select "Bob", you're not selecting ID 1, 2 and 3. You'd be say selecting ID 1. We'd need to do a lookup based on the value "Bob" at some point to find the other two.

2024-06-14 14:17 UTC, philipnye commented
Thanks Graham!

> I'll need to look into the count() stuff, your suggestion make sense, I just need to work out how to implement it into what we've got in PHP.

If this is more than a small task, happy to defer it and merge the scripts in as they are, and sort when we handle the query edits I'll be writing. Let me know.
 
> I'll need to dig a bit deeper into exactly why some things are names vs ids, but from memory it's because of the multiple results for the autocomplete if they're not grouped/distinct.
> 
> e.g. the autocomplete field is showing
> 
> * Bob
> * John
> * Steve
> 
> But without the grouping or distinct (can't remember which) the autocomplete would show as
> 
> * Bob
> * Bob
> * Bob
> * John
> * Steve
> * Steve
> 
> When you select "Bob", you're not selecting ID 1, 2 and 3. You'd be say selecting ID 1. We'd need to do a lookup based on the value "Bob" at some point to find the other two.

So, I've checked. In the `person` table, which forms the basis of the query 1 autocomplete, there's currently one duplicate use of a `display_name`. This is erroneous - I'll remove it next time I do a data update. We're using `display_name` to try and ensure uniqueness, otherwise all of the query 1 queries fall down (i.e. you'd have two people's data showing in the table). So I don't think there's any danger in running `1_related_content.sql` based on ID/`@minister_ids` too. 

In the `post` table, which forms the basis of the query 2 autocomplete, multiple records can share a `display_name`. These are things we want to be considered a single role, but where some characteristic of the role has changed (e.g. what department it's based at). I might need you to check the query 2 autocomplete, but I think it must be returning multiple IDs, which are then passed to `2_table_data_merged.sql` etc. because e.g. doing a search for 'Minister for London' on the staging site correctly returns Minister for London appointments based at multiple departments. If multiple IDs are being passed to the other queries, I think it'd make sense to pass the same thing (`@role_ids`) to `2_related_content.sql`. We do perhaps need to throw a `distinct` onto `2_related_content.sql`, which I didn't have (or a `select..limit 1). But all roles that share a `display_name` have the same `id_ifg_website` - and will do going forward, because we consider them functionally to be a single role - so nothing is lost by using `@role_ids` rather than `@name` 😄

2024-06-27 13:13 UTC, graham73may commented on sql/1_appointments_held_by_person/1_related_content.sql
For `1_table_data_merged.sql`, the journey the form and the code goes on is: 

1. User enters `David Cameron`
2. The string is passed through [`queryForMinisterIdsByMinisterName()`](https://gitlab.com/sb-dev-team/instituteforgovernment.org.uk/-/blob/feature__ministers/web/modules/custom/ifg_ministers/src/Form/MinistersRolesOfIndividualForm.php?ref_type=heads#L82) to convert it to an array of IDs.
3. Added as a condition to both merged and unmerged query [here](https://gitlab.com/sb-dev-team/instituteforgovernment.org.uk/-/blob/feature__ministers/web/modules/custom/ifg_ministers/src/SqliteQuery/MinistersRolesOfIndividualQueries.php?ref_type=heads#L339)

So somewhere in the process, it is still doing string with name -> lookup IDs based on the string. 

I can adjust the related content to use the IDs returned by `queryForMinisterIdsByMinisterName()`. 

I'll push up to this repo once I've implemented the change.

2024-06-27 13:30 UTC, graham73may commented on sql/1_appointments_held_by_person/1_related_content.sql
Related commit:
https://gitlab.com/sb-dev-team/instituteforgovernment.org.uk/-/commit/b59f3aa6a42b61727d9860836809798a797cecfa

2024-06-27 13:53 UTC, graham73may commented on sql/2_persons_holding_appointment/2_related_content.sql
> +    name = @role
Updated

2024-06-27 14:05 UTC, graham73may commented on sql/1_appointments_held_by_person/1_table_data_merged.sql
> +            minister_id IN (@id)
Updated

2024-06-27 14:06 UTC, graham73may commented on sql/1_appointments_held_by_person/1_table_data_unmerged-result-count.sql
> +    minister_id IN (@id)
Updated

2024-06-27 14:38 UTC, graham73may commented on sql/1_appointments_held_by_person/1_table_data_merged-result-count.sql
Commit related to this on our side: 
https://gitlab.com/sb-dev-team/instituteforgovernment.org.uk/-/commit/afc216d651b5852df1b44b999fededcabb6b672f

2024-06-27 14:41 UTC, graham73may commented on sql/1_appointments_held_by_person/1_table_data_merged-result-count.sql
I've pushed changes for this to my fork, I've also applied the changes to the minister tool (I still need to fully test every query integration in the tool - both merged and un-merged mode)

2024-06-27 14:41 UTC, graham73may commented on sql/2_persons_holding_appointment/2_table_data_merged-result-count.sql
Pushed

2024-06-27 14:41 UTC, graham73may commented on sql/4_appointments_exits_between_dates/4_table_data_merged-result-count.sql
Pushed

2024-06-27 14:41 UTC, graham73may commented on sql/3_appointments_at_date/3_table_data_merged-result-count.sql
Pushed

2024-06-27 15:00 UTC, graham73may commented
Just to respond to these points: 

> So, I've checked. In the person table, which forms the basis of the query 1 autocomplete, there's currently one duplicate use of a display_name. This is erroneous - I'll remove it next time I do a data update. We're using display_name to try and ensure uniqueness, otherwise all of the query 1 queries fall down (i.e. you'd have two people's data showing in the table). So I don't think there's any danger in running 1_related_content.sql based on ID/@minister_ids too.

Great! Please re-check these changes in my recent push.

> In the post table, which forms the basis of the query 2 autocomplete, multiple records can share a display_name. These are things we want to be considered a single role, but where some characteristic of the role has changed (e.g. what department it's based at). I might need you to check the query 2 autocomplete, but I think it must be returning multiple IDs, which are then passed to 2_table_data_merged.sql etc. because e.g. doing a search for 'Minister for London' on the staging site correctly returns Minister for London appointments based at multiple departments. If multiple IDs are being passed to the other queries, I think it'd make sense to pass the same thing (@role_ids) to 2_related_content.sql. We do perhaps need to throw a distinct onto 2_related_content.sql, which I didn't have (or a select..limit 1). But all roles that share a display_name have the same id_ifg_website - and will do going forward, because we consider them functionally to be a single role - so nothing is lost by using @role_ids rather than @name 😄

Great, this matches the changes I've submitted in my recent push.

2024-06-27 15:32 UTC, philipnye requested changes

2024-06-27 15:32 UTC, philipnye commented on sql/1_appointments_held_by_person/1_related_content.sql
Minor, but I think it would be worth using `@minister_ids` as the placeholder here too for consistency with the other query 1 scripts?

2024-06-27 15:35 UTC, philipnye commented
> Hi @philipnye
> 
> I've made the further placeholder name changes.
> 
> I've reverted the related content queries to use ID and refactored how our code works with these. Please see comments above about where the IDs come from.
> 
> I've implemented the `SELECT COUNT(1) FROM( ... )` nesting approach, seems to work so far on our side but I'll fully test this tomorrow and deploy.
> 
> Very keen for this to get merged in so we're back on a level playing field!
> 
> Thanks,

Thanks, @graham73may. There's one minor comment I've added re: consistency of a placeholder name but then happy to merge once you've had chance to test the result count approach and are happy with that.

2024-06-27 17:05 UTC, graham73may commented on sql/1_appointments_held_by_person/1_related_content.sql
Ah sorry, I just rolled back to the original and added `IN`. Updated now.

2024-06-28 12:32 UTC, graham73may commented
Hi @philipnye,

Queries 1-4 tested, results appearing and paginating (hopefully resolves a couple of the pagination bug reports at the same time!). 

I'll get this deployed to the staging site now. Looking forward to this PR being merged! 

Thanks,

2024-06-28 13:38 UTC, philipnye commented
Great - thank you for getting this done!

As mentioned previously, I'll merge and at some point fix some whitespace that hasn't come in correctly and flag to you - though may not be this side of the election.

Thanks!

2024-06-28 13:38 UTC, merged